# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

next_combination <- function(n, first_comb) {
    .Call(`_HyperSBM_next_combination`, n, first_comb)
}

next_combination_rep <- function(n, first_comb) {
    .Call(`_HyperSBM_next_combination_rep`, n, first_comb)
}

next_permutation <- function(first_perm) {
    .Call(`_HyperSBM_next_permutation`, first_perm)
}

bin_coeff <- function(n, m) {
    .Call(`_HyperSBM_bin_coeff`, n, m)
}

find_comb <- function(n, comb) {
    .Call(`_HyperSBM_find_comb`, n, comb)
}

find_comb_rep <- function(n, comb) {
    .Call(`_HyperSBM_find_comb_rep`, n, comb)
}

compute_Y <- function(n, M, list_edges) {
    .Call(`_HyperSBM_compute_Y`, n, M, list_edges)
}

compute_B <- function(n, M, tau, Y, all_latents, model, n_threads) {
    .Call(`_HyperSBM_compute_B`, n, M, tau, Y, all_latents, model, n_threads)
}

compute_pi <- function(tau) {
    .Call(`_HyperSBM_compute_pi`, tau)
}

compute_ELBO <- function(M, tau, pi, Y, B) {
    .Call(`_HyperSBM_compute_ELBO`, M, tau, pi, Y, B)
}

compute_tau_par <- function(M, tau_prec, pi, Y, B, n_threads) {
    .Call(`_HyperSBM_compute_tau_par`, M, tau_prec, pi, Y, B, n_threads)
}

VE_step_par <- function(M, tau_old, pi, Y, B, tol, maxit, n_threads) {
    .Call(`_HyperSBM_VE_step_par`, M, tau_old, pi, Y, B, tol, maxit, n_threads)
}

VEM_par <- function(M, Q, n, tau_old, all_latents, Y, tol, maxit_VEM, maxit_FP, model, start, print, n_threads) {
    .Call(`_HyperSBM_VEM_par`, M, Q, n, tau_old, all_latents, Y, tol, maxit_VEM, maxit_FP, model, start, print, n_threads)
}

compute_LogLik <- function(n, M, Q, tau, pi, Y, B) {
    .Call(`_HyperSBM_compute_LogLik`, n, M, Q, tau, pi, Y, B)
}

